---
# This playbook will ensure that all baremetal compute nodes are named after
# their inventory host names. It matches the ipmi address in the inventory to
# the one gathered from inspection

- name: Set baremetal compute nodes resource class
  hosts: controllers[0]
  gather_facts: False
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
  pre_tasks:
    - name: Set up openstack cli virtualenv
      pip:
        virtualenv: "{{ venv }}"
        name:
          - python-openstackclient
          - python-ironicclient

- name: Set baremetal compute nodes resource class
  hosts: baremetal-compute
  gather_facts: False
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
    controller_host: "{{ groups['controllers'][0] }}"
  tasks:
    - name: Set resource class
      command: >
        {{ venv }}/bin/openstack baremetal node set --resource-class "{{ ironic_resource_class }}" "{{ inventory_hostname }}"
      delegate_to: "{{ controller_host }}"
      environment: "{{ openstack_auth_env }}"
      vars:
        # NOTE: Without this, the controller's ansible_host variable will not
        # be respected when using delegate_to.
        ansible_host: "{{ hostvars[controller_host].ansible_host | default(controller_host) }}"
      when: ironic_resource_class is defined
